package main

import "fmt"

/*

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

func SumEvenFibonacciNumbers(below int) int {
	fib := NewFibonacci()
	sum := 0
	for {
		v := fib.Next()
		if v > below {
			return sum
		}
		if v%2 == 0 {
			sum += v
		}
	}
}

func Problem002() {
	fmt.Println("Problem 2 - Sum of terms in the Fibonacci sequence whos value do not exceed four million:", SumEvenFibonacciNumbers(4000000))
}
